services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=
  #     - LOG_LEVEL=info
  #     - SCRAPE_TIMEOUT=30000
  #     - REQUEST_TIMEOUT=5000
  #   depends_on:
  #     - redis
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
